version: '3.8'
services:
  jupyter_notebook:
    restart: always
    build: jupyter
    volumes:
      - /home/alex/rig1/projects/pc:/home/jovyan/work
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
