version: '3.8'
services:
  jupyter_notebook:
    restart: always
    build: jupyter
    volumes:
      - /home/alex/rig1/projects/pc:/home/jovyan/work
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
