version: '3.8'
services:
  jupyter_notebook:
    build: jupyter
    volumes:
      - ./jupyter/src/:/home/jovyan/work
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
