#FROM jupyter/scipy-notebook:33add21fab64
#FROM jupyter/tensorflow-notebook:ubuntu-20.04 # no gpu
#FROM durgeshm/jupyter-tensorflow-gpu:latest # tf 1 gpu ok
FROM yhavinga/jupyter-tensorflow-pytorch-gpu:tensorflow2.1.0-pytorch1.4.0-cuda10.1-ubuntu18.04
EXPOSE 8888
#RUN apt-get update && apt-get install -y iputils-ping
